# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa4867a42c47e815aff74c0f2bdb3ebe64468237c5016820b8a8611693b0e551a3d2e584656343e68b054130053700b53e4d328e2b7b5089d0f65fb784cd9275

test:
  secret_key_base: 3b2271dbb52593f2bba9da963adca1086a3427a0f959e3602528900b987d2183428662ffc4177fb5c0a927fa53f69755cbe7709ceade3cfb8cc82bec51141e3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
